In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("sales.db")

In [3]:
df = pd.read_sql("SELECT * FROM sales_data", conn)

In [4]:
 print(df)

   Order_ID  Product     Category  Sales  Quantity  Profit
0      1001   Laptop   Electonics  50000         1    8000
1      1002    Mouse   Electonics    800         2     200
2      1003    Chair    Furniture   4500         1     700
3      1004    Table    Furniture   6500         1     900
4      1005  Printer  Electronics  12000         1    2500

In [5]:
pd.read_sql("SELECT * FROM sales_data", conn)

   Order_ID  Product     Category  Sales  Quantity  Profit
0      1001   Laptop   Electonics  50000         1    8000
1      1002    Mouse   Electonics    800         2     200
2      1003    Chair    Furniture   4500         1     700
3      1004    Table    Furniture   6500         1     900
4      1005  Printer  Electronics  12000         1    2500

In [6]:
pd.read_sql("SELECT * FROM sales_data WHERE Category='Electronics';", conn)

   Order_ID  Product     Category  Sales  Quantity  Profit
0      1005  Printer  Electronics  12000         1    2500

In [7]:
pd.read_sql("SELECT * FROM sales_data ORDER BY Sales DESC;", conn)

   Order_ID  Product     Category  Sales  Quantity  Profit
0      1001   Laptop   Electonics  50000         1    8000
1      1005  Printer  Electronics  12000         1    2500
2      1004    Table    Furniture   6500         1     900
3      1003    Chair    Furniture   4500         1     700
4      1002    Mouse   Electonics    800         2     200

pd.read_sql("SELECT * FROM sales_data ORDER BY Sales DESC LIMIT 3;", conn)

In [8]:
pd.read_sql("""SELECT Category, SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Category;
""", conn)

      Category  Total_Sales
0   Electonics        50800
1  Electronics        12000
2    Furniture        11000

In [9]:
conn.close()